### ISSUE TITLE
Front-end cleanup

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#10]
Play
- [x] Add subcopy to . each drag space to explain what to do, fix section hieght and spacing, advanced tools section for each box. (design in progress)

**Comment by benwong0** [comment]
@harikmenon Do you have a screenshot for this: Sign in button falls down on mobile?

**Comment by harikmenon** [comment]
@julskast can you explain?

**Comment by julskast** [comment]
![image1](https://user-images.githubusercontent.com/764613/31951657-c2cad7a6-b8ac-11e7-9a3d-e71a1c08ebd2.PNG)
Image attached @benwong0. While the page is loading you see a big old mess. Once loaded, looks ok. Solution could be to hide until loaded, etc. vs fully fixing.

**Comment by toannguyen132** [comment]
@harikmenon can you explain me about this issue? I am not sure what does it mean.
`Reduce font size for table header for nemisis board on mobile (or make it scroll like the rest of the table)`

**Comment by harikmenon** [comment]
the whole page scrolls and not just the table the last time i checked, if its fixed you can close that item.

**Comment by toannguyen132** [comment]
@harikmenon 
About this issue:
`Gif stops spinning: feels broken when it stops. Could we change the message when it’s done that says something like “almost there”?`

Because parsing game is a heavy task, it makes the gif stop spinning. However, there is no event at that time so I can not hook into. 

I can change the message 'parsing replay, please wait...' to 'almost done' if you want.

**Comment by harikmenon** [comment]
Completed
