### ISSUE TITLE
Tier and language filters do not work correctly

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#107]
1. https://forums.halite.io/t/tier-system-in-leaderboard-does-not-work/283
2. https://github.com/HaliteChallenge/Halite-II/issues/139

**Comment by benwong0** [comment]
@harikmenon seems to be working for me
<img width="584" alt="screen shot 2017-10-27 at 1 32 25 pm" src="https://user-images.githubusercontent.com/5994802/32124058-5770b7de-bb1b-11e7-9a84-aa63f48a44b2.png">

any other details on this bug?

**Comment by harikmenon** [comment]
No if you select silver, you are only seeing one person there are many silver and gold.

**Comment by harikmenon** [comment]
@lidavidm : do you know what could be going wrong here?

**Comment by lidavidm** [comment]
Ah yeah, I need to process the tier filter on the backend a little less literally.

**Comment by lidavidm** [comment]
Ah wait, that API query is for getting a single person of a specific rank, not a specific tier. Tier should be something like https://api.halite.io/v1/api/leaderboard?offset=0&limit=25&filter=tier,%3E,Gold but right now, using `tier,=,Gold` will give you only the person whose rank is exactly on the cutoff for Gold, and not all Gold players. Something like `tier,>,Silver` does work though, but I will change it so that `=` works.
