### ISSUE TITLE
publish hlt_client to pypi

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#109]
From Halite email account:

https://halite.io/learn-programming-challenge/halite-cli-and-tools/halite-client-tools

shows ​`hlt_client` to be the name of the PyPi package, but I manually downloaded your zip and instaled it and saw that it is actually named `hlt-client`

➜  ~ pip3 freeze | grep hlt 
hlt-client==1.0

and doesn't appear to be on PyPi at all.

➜  ~ pip3 install hlt-client
Downloading/unpacking hlt-client

  Could not find any downloads that satisfy the requirement hlt-client

and 404 here https://pypi.python.org/pypi/hlt-client

Been enjoying this game a lot! Thanks for putting it together.

**Comment by wizzup** [comment]
If you do this, please also change the name of script from `client.py` to proper one.

**Comment by j-clap** [comment]
Done. "pip3 install hlt_client" or "python3 -m pip install hlt_client" to install, "hlt" to run

**Comment by wizzup** [comment]
@j-clap Can you make some small changes? I am not be able to run this on NixOS because

* package name is `hlt-client` but file name is `hlt_client` -> need to be the same name
* file extension uploaded on pypi is `whl` -> need `zip` or `tar.gz`

I think you don't need to change anything with the old uploaded one, just upload a new one.
