### ISSUE TITLE
Non-zero velocities causing docking to fail

### ISSUE THREAD

**Issue by fohristiwhirl** [HaliteChallenge/Halite-II#114]
Drag isn't guaranteed to reduce velocity to exactly zero. Sometimes a ship's velocity ends up being something like 1e-16 or so.

But the [can_dock() method](https://github.com/HaliteChallenge/Halite-II/blob/2ff792f77a3f485cfaa1253ad72488dac7aef30c/environment/core/Entity.hpp#L184) checks if a ship's velocity is exactly 0.

Therefore, docking can fail for no apparent reason.

**Comment by Janzert** [comment]
Haven't tested this to be sure, but my current guess is that the root cause is the code to limit a ships velocity can have floating point rounding errors that allow it to go slightly too high.

This code is located at [environment/core/Entity.cpp, lines 43-47](https://github.com/HaliteChallenge/Halite-II/blob/3286b3c4246a0f635a70b9f188212d6fd3a7d42e/environment/core/Entity.cpp#L43)

**Comment by fohristiwhirl** [comment]
This line is also relevant:

https://github.com/HaliteChallenge/Halite-II/blob/2ff792f77a3f485cfaa1253ad72488dac7aef30c/environment/core/Halite.cpp#L361

One could perhaps change that to:

``` if (magnitude <= drag + 0.1)``` or somesuch

**Comment by Janzert** [comment]
yeah, that fixes it one level up. I'm just wondering if magnitude larger than MAX_SPEED can cause problems anywhere else though.

**Comment by harikmenon** [comment]
@lidavidm : can you comment?

**Comment by lidavidm** [comment]
@Janzert is correct, we should just truncate all our velocities.

**Comment by Janzert** [comment]
I think setting the floating point round mode as 'toward zero', then doing all the calculations as long doubles and only converting the final results to double should make it as accurate as possible while not getting a result that is larger than the limit.

Actually just rereading the code there is a larger bug than just float rounding. The test to see if the velocity exceeds max_speed just checks the old velocity. The new velocity hasn't been applied to the object yet but is just held in new_vel_x and new_vel_y.

https://github.com/HaliteChallenge/Halite-II/blob/3286b3c4246a0f635a70b9f188212d6fd3a7d42e/environment/core/Entity.cpp#L43

**Comment by lidavidm** [comment]
@fohristiwhirl good catch, @Janzert thanks for the suggestion. I'll test it out and fix that bug, though it's probably safest just to reset velocities.

**Comment by fohristiwhirl** [comment]
If you want the game engine to continue having drag as a (currently unused) concept you could just make can_dock() have the test:

```
velocity.vel_x > -0.01 && velocity.vel_x < 0.01
velocity.vel_y > -0.01 && velocity.vel_y < 0.01
```

Or such.

**Comment by lidavidm** [comment]
Actually it seems the fixing the bug @Janzert found is enough to prevent the problem, even without setting the rounding mode. If we cap the velocity properly, then there is already a branch in the drag calculation that resets the velocity to 0 (instead of using deceleration).

**Comment by ruilov** [comment]
@lidavidm it doesn't look like the fix in #129 was sufficient, and this failure to dock issue still happens. Attached is a simple log file that demonstrates the issue. On the 6th turn the ship should've docked. Log file says "engine_version": "1.2.332.gdc32", hopefully that's the latest.
[bug.zip](https://github.com/HaliteChallenge/Halite-II/files/1564988/bug.zip)

**Comment by ruilov** [comment]
Cool. I do have version 1.2.332.gdc32 after downloading the starter pack for C++ MacOS just a couple of hours ago.

**Comment by lidavidm** [comment]
@ruilov I'm traveling all day today but will take a look at this when I
can. Looks like something is out of sync.

**Comment by Janzert** [comment]
Not directly relevant to the problem but I'll try and clarify the version numbers a bit.

Basically the format is the first two numbers are a tag in the repo, next is the number of commits since the tag and finally the last set of characters is a git commit id (with 'g' prepended). In other words it is the output of `git describe` with dashes replaced by dots.

Unfortunately for whatever reason at least one of the repos used to build the binaries doesn't seem to pull in new tags and has been stuck on 1.2. In fact finding the git commits referenced in the above two versions, version `1.2.332.gdc32` is newer from around November 20th dc3200e798c96a248a5cbb9d0144bd5f1d096fe7 while `1.5.18.gfd10` is from November 17th fd10d9b9889bfc135b29c6563a1c088432f274b6

**Comment by lidavidm** [comment]
I think this is just a case of the OSX binary being built from the wrong version somehow, since the binaries in the other starter kits report `1.5.18.gfd10`, the same version that @fohristiwhirl found. I wonder what version the binary actually is, since it might have pulled in a misleading `version.hpp`.

Unfortunately, as far as I can tell from reading the disassembled OSX binary, it does have the fix in #129. So at this point, we might as well just hard-cap the velocity.

**Comment by lidavidm** [comment]
Ah, and it seems the magnitude of the resulting velocity (7 units @ 271 degrees) is slightly over 7 (7.000000000000001) so it uses `accelerate_by` to decelerate. I'm just going to get rid of the other code path and prevent this once and for all.

**Comment by fohristiwhirl** [comment]
Does the bug reproduce? I couldn't get it to happen on whatever my version really is.

**Comment by lidavidm** [comment]
I didn't try reproducing, but at least in Python this happens:

```
>>> import math
>>> vx = 7 * math.cos(math.radians(271))
>>> vy = 7 * math.sin(math.radians(271))
>>> (vx, vy)
(0.12216684506098191, -6.998933866094739)
>>> math.sqrt(vx*vx + vy*vy)
7.000000000000001
```
so the fix in #129 doesn't matter at all.

**Comment by fohristiwhirl** [comment]
The following should reproduce, but doesn't for me. Run with...
`halite.exe -s 1 -q -d "240 160" "python repro.py" "python repro.py"`

```python
pid = int(input())

for n in range(2):
	input()

print("test")

turn = -1

while 1:
	input()
	turn += 1

	if pid == 0:
		print()
		continue

	if turn == 0:
		print("t 4 1 271")
	elif turn == 1:
		print("t 4 6 271")
	elif turn >= 2 and turn <= 4:
		print("t 4 7 271")
	elif turn == 5:
		print("d 4 0")
	else:
		print()
```

**Comment by lidavidm** [comment]
Hmm, you're right, it doesn't happen for me either, even going back to the commit that the buggy version supposedly is on. It's also not just a matter of Clang on OSX vs GCC on Linux or MSVC on Windows, since I just tried Clang. I don't have access to a Mac, though.
