### ISSUE TITLE
Mismatch between planet explosion code, comments, and documentation

### ISSUE THREAD

**Issue by Billiam** [HaliteChallenge/Halite-II#219]
### docs 

> When a planet dies, it explodes, dealing damage to any ships or planets within 10 units of the planet surface. The damage scales linearly with distance from the surface, beginning at 255 damage when adjacent to the planet and ending at 51 damage if 5 units away.

### code
Logic is here: https://github.com/HaliteChallenge/Halite-II/blob/11b7d6c1abc588d0de250b854d9d47963077b786/environment/core/Halite.cpp#L71-L84

Where `distance` is center of planet to closest edge of the target (ship or other planet), `distance_from_crust` is the distance from planet crust to the closest edge of the target, and `max_distance` is the higher of the docking radius constant (4) or the planet's radius.

Only ships within `max_distance` are considered for this method, so any damage scaling beyond the planet radius (or docking distance) is ignored.

I think the damage is closer to this (but could be wrong, can somebody verify?)

radius | distance | damage
-- | -- | --
2 | 0 | 1275
2 | 2 | 1211.25
2 | 4 | 1147.5
4 | 0 | 1275
4 | 4 | 1147.5
8 | 0 | 1275
8 | 4 | 1211.25
8 | 8 | 1147.5

**Comment by jenheilemann** [comment]
Assuming the docs are correct and the code is not, I think it should look more like this:

```ruby
# this is 0 when the ship is at max_distance, and 1 when distance from crust == 0
ratio = (max_distance - distance_from_crust)/max_distance
# 204 == 255 - 51
# 204*ratio is the fluctuation based on distance_from_crust
damage = 204*ratio + 51
```

This is assuming that max_distance passed into the function is 10, as the docs say, or could still work correctly if max_distance is the greater of planet radius or docking radius. 

Potentially, the docs need to be updated, since it kind of makes sense that it should be possible to completely destroy a totally healthy ship if they're too close to an exploding planet.  In the above calculation, the 204 number could be adjusted up to allow for overkill on a linear curve, or a minimum distance could be established and the "distance_from_crust" number could be adjusted to be a "distance_from_kill_line" or similar. A ratio with a value > 1 in that case would just be overkill, and represent a ship that's too close to the exploding planet. Like this: 

```ruby
# instadeath is always inside the docking radius, outside it is a linear function
# probably a better formula if max_distance is a constant (such as 10, like the docs say)
distance_from_kill_line = distance - planet.radius - GameConstants::DOCKING_RADIUS
ratio = (max_distance - distance_from_kill_line)/max_distance
damage = 204 * ratio + 51
```

Or possibly:
```ruby
# instadeath is a function of the length of max_distance
# probably a better formula if max_distance continues to be dependent on the planet radius
distance_from_crust = distance - planet.radius
ratio = (max_distance - distance_from_crust)/max_distance
damage = 300 * ratio + 51
# plugging in some numbers,
# if max_distance == 10, instadeath is at distance_from_crust = 3.2
# if max_distance == 4, instadeath is at distance_from_crust = 1.28
# If you change 300, bigger makes the instadeath circle a larger portion of the max_distance
```

**Comment by Janzert** [comment]
I took a quick look at this earlier today, but didn't have time to do anything further at that point. Thanks for filing an issue.

The Docs, the code comment in the function and what the code actually does are certainly three different things. What actually happens currently is any ship that is within the max_distance from the planet edge will be killed (they are guaranteed to receive more than 255 units of damage). Where max_distance is defined as max(4, planet_radius).

The way I went about implementing behavior corresponding to the code comment was to replace the current damage formula with:
    max_damage = 5 * max_ship_hp
    min_damage = 0.5 * max_ship_hp
    distance_factor = (distance_from_crust / max_distance)
    damage = max_damage - distance_factor * (max_damage - min_damage)

This would basically allow a ship at full health to survive if it was at over ~90% of max_distance from the planet. So it's not a huge change from current behavior, but the cliff of taking 50% damage at max_distance to taking 0 damage just beyond doesn't make a lot of sense to me.

The documentation behavior of taking full damage at the surface to 50 points of damage at a distance of 5 seems like too large of a change from current behavior.

**Comment by lidavidm** [comment]
The docs on this point sound like they're left over from an earlier iteration. I should point out that nearby planets, if close enough, are also damaged, and so the exact damage matters, though generally this should only happen for the cluster of planets in the center.

@j-clap What do you think is the best way of handling this? I would probably go with updating the code to match the comment, since I don't think one planet exploding and hitting another is all that common anyways (though maybe nobody is exploiting it at the moment).

**Comment by Janzert** [comment]
From what I can tell reading the code the center planets will always be generated farther apart than the explosion distance. The other planets are forced to be at a distance of at least 5 edge to edge, so planets with a radius over 5 could be close enough to damage another planet when exploding. But seems like that's going to be pretty rare.

**Comment by harikmenon** [comment]
@lidavidm sounds good to me. Lets do it.

**Comment by Billiam** [comment]
I think this new logic backwards:

```
const auto damage = min_damage + (distance_from_crust / max_distance) * (max_damage - min_damage);
```
At a close distance (1) to a planet with a radius of 4

```
auto_damage = 127.5 + (1 / 4) * (1275 - 127.5)
```
At the maximum distance
```
auto_damage = 127.5 + (4 / 4) * (1275 - 127.5)
```

**Comment by lidavidm** [comment]
@Billiam good catch, my mistake.
