### ISSUE TITLE
Reset TS bots rating

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#221]
Reset ratings for non ts* bots that haven't been updated since the public competition launched.

**Comment by j-clap** [comment]
Will do this first thing tomorrow :)

**Comment by harikmenon** [comment]
Sweet. Lets not update our bot bosses, everyone else who hasnt submitted a bot in the last 14 days is game.Thanks jack!

**Comment by Janzert** [comment]
What is this solving?

The only issue I was aware of was caused by the low sigmas these bots had managed to obtain. Since the tau bump on Thursday morning, the lowest sigma of active players has gone from 0.013 to over 0.1 already. They will continue climbing to somewhere around 0.218 making them only 0.07 less than a 500 game bot.

**Comment by j-clap** [comment]
People have been complaining ts bots are erroneously ranked since they pre-played and have a greater certainty and inflation in their score. I do agree with your point, but at the same time I agree with the users who point out the scores are slightly inflated. We're just resetting their sigma, so worst case they'll just go back to where they were.

**Comment by Janzert** [comment]
Here's charts of the sigmas from just before the tau change and now
![sigma-11-02-tau0](https://user-images.githubusercontent.com/392930/32420437-490db658-c258-11e7-9915-2a3eb6a4099d.png)
![sigma-11-05-tau008](https://user-images.githubusercontent.com/392930/32420438-491b4282-c258-11e7-8826-1714eb79382f.png)

You can see beta competitors are almost already even with post launch competitors,

Just resetting the sigmas will mean they take quite a long time to get enough games to come back down since they won't be getting the extra game bonus for new bots. For instance zxqfl resubmitted ~12 hours after the tau change and has received over 500 games already, but daewook has only been in 206 since the change first happened.

**Comment by j-clap** [comment]
Can't say no to solid data. Hari, you okay with this being closed considering the new data?

**Comment by Janzert** [comment]
Also I want to reiterate that as I said in the initial tau bump issue, I do plan to continue monitoring the sigmas to ensure that it takes a week or less to get a sigma that is reasonably<sup>1</sup> close to the base value.

<sup>1</sup> I know that's a bit vague and I haven't completely thought through a hard number, but call it something like < 0.1 difference so the rating advantage to long playing bot is < 0.3.

**Comment by harikmenon** [comment]
Yep. lets close it. Thanks @Janzert

**Comment by mellendo** [comment]
Thanks for the bump, it helped, but daewook and tsadmiral still have significantly inflated ratings.  When tsadmiral was originally submitted, after a week, it settled in at 44.84.  When I resubmitted my bot, this allowed tsadmiral to move to the top 3 hardware where it was only playing 2 player games, & its rating quickly climbed to 46.81.  It continued to climb while playing only 2 player games, but now has come back down a bit, but still far above where it would be if you resubmitted the bot.

If you doubt that there is a problem, I highly encourage you to resubmit the code for the tsadmiral bot.  It will very likely settle in at least 1 point below its current rating of 46.96.  

Daewook's bot needs the same reset/resubmit.  These are the only 2 that were on the top 3 hardware, that haven't been resubmitted since the change.

FYI, for reference, when I was on the top 3 hardware, my rating was 46.16.  After I resubmitted, my bot settled in at 43.01.  I have made significant improvements to my bot since then, & I am still below 46.16.

**Comment by Janzert** [comment]
I won't have time to really look at this in depth until tomorrow. So just a few quick notes for now. The extremes of the ratings will almost always over and under shoot what they should really be. This isn't unique to trueskill and will happen with pretty much any rating system. In this case because of the pairing system used in beta only pairing the top 2 against each other it probably inflated daewook even further. If daewook is still inflated relative to the other top bots (which wouldn't be surprising), the tau bump was meant to correct this as well since the mu will become significantly more fluid as sigma increases.

**Comment by mellendo** [comment]
I understand that ratings systems will have extremes.  The tau bump did help, as daewook/tsadmiral drifted down about .5, but they are still inflated.  If you do the tau bump a few more times, or resubmit the code, you will almost certainly see them drift down around 1 point further.

**Comment by Janzert** [comment]
Sorry I didn't get to this yesterday, I got distracted and ended up spending all my halite time on engine problems.

Below are some cross tables for the top 15 players. The rows are the win rate against the person in that column or conversely the columns are the loss rate against the person in that row.

The first table is one using the conservative ratings as used for the site rankings. But since we're talking about a possible inaccuracy in mu, in this case it's better to use a "best guess" ranking, i.e. just straight mu ranking. That is the second table below. The final table is the raw game results. As you can see number of games is generally very small so the win rates are going to be very uncertain, but it at least can give us an idea on how a player is doing against the field.

As you can see in the mu ranking, with the exception of winning against the person (ewirkerman) just above him and losing to the person (reCurs3) just below him, daewook loses to everyone else above him and beats everyone else below him. So his placement of mu isn't terribly out of line, of course taking 1 off his mu only moves him down below tsadmiral. Which does put him below reCurs3 (better), but also pushes him farther below ewirkerman (worse).

    Conservative ranking:
    Name		zxqfl	shummi	Vlad-S	daewoo	0x726b	tsadmi	ewirke	reCurs	mellen	SpaceS	Rokhan	bovard	fohris	nkelly	MELLMA
    zxqfl		...	54.5%	57.1%	60.0%	64.9%	80.0%	63.6%	71.0%	65.0%	76.5%	86.7%	83.3%	100.0%	100.0%	83.3%
    shummie		45.5%	...	57.6%	60.0%	63.0%	62.5%	51.6%	68.3%	69.0%	66.7%	83.3%	72.2%	66.7%	81.8%	83.3%
    Vlad-Shc	42.9%	42.4%	...	62.5%	44.0%	68.8%	45.2%	51.6%	54.7%	49.7%	60.7%	52.2%	88.9%	71.4%	33.3%
    daewook		40.0%	40.0%	37.5%	...	26.7%	50.3%	60.0%	20.0%	54.2%	58.3%	55.6%	100.0%	0.0%	100.0%	50.0%
    0x726b00	35.1%	37.0%	56.0%	73.3%	...	61.5%	61.4%	69.1%	65.3%	63.0%	59.5%	52.5%	71.4%	60.7%	80.0%
    tsadmira	20.0%	37.5%	31.2%	49.7%	38.5%	...	42.9%	36.4%	50.8%	42.9%	68.8%	83.3%	50.0%	75.0%	50.0%
    ewirkerm	36.4%	48.4%	54.8%	40.0%	38.6%	57.1%	...	47.5%	75.0%	66.7%	57.1%	100.0%	60.0%	75.0%	100.0%
    reCurs3		29.0%	31.7%	48.4%	80.0%	30.9%	63.6%	52.5%	...	51.0%	64.3%	70.6%	81.2%	50.0%	80.0%	57.1%
    mellendo	35.0%	31.0%	45.3%	45.8%	34.7%	49.2%	25.0%	49.0%	...	50.8%	59.9%	75.6%	52.2%	58.3%	72.7%
    SpaceShi	23.5%	33.3%	50.3%	41.7%	37.0%	57.1%	33.3%	35.7%	49.2%	...	47.2%	52.3%	50.0%	51.0%	55.2%
    Rokhan		13.3%	16.7%	39.3%	44.4%	40.5%	31.2%	42.9%	29.4%	40.1%	52.8%	...	46.2%	69.6%	53.9%	49.3%
    bovard		16.7%	27.8%	47.8%	0.0%	47.5%	16.7%	0.0%	18.8%	24.4%	47.7%	53.8%	...	54.2%	52.1%	54.0%
    fohristi	0.0%	33.3%	11.1%	100.0%	28.6%	50.0%	40.0%	50.0%	47.8%	50.0%	30.4%	45.8%	...	64.7%	55.0%
    nkelly13	0.0%	18.2%	28.6%	0.0%	39.3%	25.0%	25.0%	20.0%	41.7%	49.0%	46.1%	47.9%	35.3%	...	43.4%
    MELLMANI	16.7%	16.7%	66.7%	50.0%	20.0%	50.0%	0.0%	42.9%	27.3%	44.8%	50.7%	46.0%	45.0%	56.6%	...

    Mu ranking:
    Name		zxqfl	shummi	0x726b	Vlad-S	ewirke	daewoo	reCurs	tsadmi	mellen	fohris	SpaceS	Rokhan	bovard	nkelly	MELLMA
    zxqfl		...	54.5%	64.9%	57.1%	63.6%	60.0%	71.0%	80.0%	65.0%	100.0%	76.5%	86.7%	83.3%	100.0%	83.3%
    shummie		45.5%	...	63.0%	57.6%	51.6%	60.0%	68.3%	62.5%	69.0%	66.7%	66.7%	83.3%	72.2%	81.8%	83.3%
    0x726b00	35.1%	37.0%	...	56.0%	61.4%	73.3%	69.1%	61.5%	65.3%	71.4%	63.0%	59.5%	52.5%	60.7%	80.0%
    Vlad-Shc	42.9%	42.4%	44.0%	...	45.2%	62.5%	51.6%	68.8%	54.7%	88.9%	49.7%	60.7%	52.2%	71.4%	33.3%
    ewirkerm	36.4%	48.4%	38.6%	54.8%	...	40.0%	47.5%	57.1%	75.0%	60.0%	66.7%	57.1%	100.0%	75.0%	100.0%
    daewook		40.0%	40.0%	26.7%	37.5%	60.0%	...	20.0%	50.3%	54.2%	0.0%	58.3%	55.6%	100.0%	100.0%	50.0%
    reCurs3		29.0%	31.7%	30.9%	48.4%	52.5%	80.0%	...	63.6%	51.0%	50.0%	64.3%	70.6%	81.2%	80.0%	57.1%
    tsadmira	20.0%	37.5%	38.5%	31.2%	42.9%	49.7%	36.4%	...	50.8%	50.0%	42.9%	68.8%	83.3%	75.0%	50.0%
    mellendo	35.0%	31.0%	34.7%	45.3%	25.0%	45.8%	49.0%	49.2%	...	52.2%	50.8%	59.9%	75.6%	58.3%	72.7%
    fohristi	0.0%	33.3%	28.6%	11.1%	40.0%	100.0%	50.0%	50.0%	47.8%	...	50.0%	30.4%	45.8%	64.7%	55.0%
    SpaceShi	23.5%	33.3%	37.0%	50.3%	33.3%	41.7%	35.7%	57.1%	49.2%	50.0%	...	47.2%	52.3%	51.0%	55.2%
    Rokhan		13.3%	16.7%	40.5%	39.3%	42.9%	44.4%	29.4%	31.2%	40.1%	69.6%	52.8%	...	46.2%	53.9%	49.3%
    bovard		16.7%	27.8%	47.5%	47.8%	0.0%	0.0%	18.8%	16.7%	24.4%	54.2%	47.7%	53.8%	...	52.1%	54.0%
    nkelly13	0.0%	18.2%	39.3%	28.6%	25.0%	0.0%	20.0%	25.0%	41.7%	35.3%	49.0%	46.1%	47.9%	...	43.4%
    MELLMANI	16.7%	16.7%	20.0%	66.7%	0.0%	50.0%	42.9%	50.0%	27.3%	45.0%	44.8%	50.7%	46.0%	56.6%	...

    Actual game counts:
    Name		zxqfl	shummi	0x726b	Vlad-S	ewirke	daewoo	reCurs	tsadmi	mellen	fohris	SpaceS	Rokhan	bovard	nkelly	MELLMA
    zxqfl		...	24	24	20	21	3	22	4	13	3	13	13	10	4	5
    shummie		20	...	51	53	16	12	41	5	40	4	24	20	13	9	10
    0x726b00	13	30	...	42	27	11	47	8	49	5	29	22	21	17	16
    Vlad-Shc	15	39	33	...	19	45	32	33	122	8	74	34	12	10	3
    ewirkerm	12	15	17	23	...	2	19	4	12	6	8	8	4	3	1
    daewook		2	8	4	27	3	...	2	10328	26	0	14	5	3	1	1
    reCurs3		9	19	21	30	21	8	...	7	26	11	18	12	13	12	4
    tsadmira	1	3	5	15	3	10204	4	...	32	1	9	11	5	6	1
    mellendo	7	18	26	101	4	22	25	31	...	12	96	88	34	21	16
    fohristi	0	2	2	1	4	2	11	1	11	...	16	7	11	11	11
    SpaceShi	4	12	17	75	4	10	10	12	93	16	...	84	56	50	32
    Rokhan		2	4	15	22	6	4	5	5	59	16	94	...	49	48	35
    bovard		2	5	19	11	0	0	3	1	11	13	51	57	...	49	54
    nkelly13	0	2	11	4	1	0	3	2	15	6	48	41	45	...	43
    MELLMANI	1	2	4	6	0	1	3	1	6	9	26	36	46	56	...

**Comment by Janzert** [comment]
> If you do the tau bump a few more times
To be clear the tau bump is an ongoing effect done at every rating adjustment. The primary effect of this is still increasing the sigma of daewook and other low sigma bots (although they are starting to level off). The secondary effect is that the mu's have and are becoming much more fluid as well.

**Comment by mellendo** [comment]
I'm not sure I understand what you mean by the tau bump is an ongoing effect.  When I click on daewook Analysis, it says the sigma is .16 .  If you reset this sigma to 1, wouldn't daewook move more than he does now with the .16 sigma?

**Comment by mellendo** [comment]
Your tables are interesting, but I think the key question is: what rating would daewook and tsadmiral settle at if their bots were resubmitted?  This is key, as this is the level that is fair to the other bots.  I believe it would be between 45 & 46.  Can you determine this somehow?  Resubmitting the tsadmiral is an easy way to determine this.  If you didn't resubmit, will they drift down to this value with the reset to sigma 1 that you did last week, or would further resetting be required?

**Comment by Janzert** [comment]
> I'm not sure I understand what you mean by the tau bump is an ongoing effect.

tau is a trueskill parameter that helps determine where how dynamic or stable the rankings are. Too dynamic and the ratings are a random walk with possibly quite large swings around the true value, too stable and the ratings won't adjust to changes in skill of either a single player or the landscape determined by the strategies of the population of players. It does this by increasing the sigma a small amount each rating update. Because of some misunderstanding of something I wrote after the contest last year, tau was originally set at 0 for this contest. This allowed the sigmas to get very small, less than 0.02 in some cases. This meant that as new players joined and old players updated and the skill landscape changed the system wasn't adjusting the mu of these low sigma players fast enough to keep up. The tau bump increased tau to a more reasonable level for the changing population of bots. This causes the low sigmas to increase each time they play a game. At this point all but one<sup>1</sup> active player is above 0.15.

<sup>1</sup> CryoBrown, he's lagging behind because at the position in the rankings he is at there aren't many new bots around (who trigger most games) and so he doesn't get as many games and therefore the sigma is adjusting slower in time though not in number of games.

> When I click on daewook Analysis, it says the sigma is .16 . If you reset this sigma to 1, wouldn't daewook move more than he does now with the .16 sigma?

Yes of course and he'd take a random walk around where he should be as his sigma came back down. 

> Your tables are interesting, but I think the key question is: what rating would daewook and tsadmiral settle at if their bots were resubmitted? This is key, as this is the level that is fair to the other bots. 

I believe this question slightly misses the primary concern. I think the root concern is whether his rating is artificially inaccurate. Secondarily if it is inaccurate will resetting the sigma help correct it.

> I believe it would be between 45 & 46. Can you determine this somehow? Resubmitting the tsadmiral is an easy way to determine this. 

If his accurate rating was at that level we would expect to see him losing to people around that level and most people above that level. Here's an updated and expanded crosstable but just including daewook's win rates, the bottom two lines show the mu and total games for each opponent.

    Name	zxqfl	shummi	ewirke	0x726b	Vlad-S	daewoo	tsadmi	reCurs	mellen	bovard	fohris	SpaceS	Rokhan	MELLMA	nkelly	kjs6x2
    daewook	0.0%	0.0%	46.7%	24.0%	39.8%	...	50.3%	26.7%	53.8%	75.0%	100.0%	58.3%	55.6%	100.0%	100.0%	80.0%
    Mu	50.88	49.72	48.49	48.16	48	47.66	47.33	47.24	46.65	46.63	45.95	45.58	45.12	44.64	44.34	44.12
    Games	3	4	15	25	83	…	20536	15	52	4	3	24	9	1	1	5

Once again the numbers are small and while he essentially ties some players he doesn't have a losing record against any of those in the 45 to 46 range. reCurs3 being the only player below his current level that he does have a losing record against.
 
> If you didn't resubmit, will they drift down to this value with the reset to sigma 1 that you did last week, or would further resetting be required?

It seems there was some confusion here and in case the above didn't clear it up, there was no sigma reset done. If the correct value for daewook's mu is or eventually becomes<sup>2</sup> 45, yes it will drift down there.

<sup>2</sup> Ratings are only meaningful relative to other ratings their absolute value holds no significance. There are a variety of things that can cause the ratings to inflate or deflate and the range to expand or contract. Also while ratings and rankings require reducing the skill measurement to just one or a few values skills for the game are actually very high dimensional. Should other players find a hole in daewook's skills and start beating him consistently the accurate mu to use for him will drop.

**Comment by mellendo** [comment]
OK, cool, thanks for the info.  Sounds like tau change fixes the problem of too small sigmas.  The slow drift down should be fine, since 5 bots are now ahead of daewook, so the inflation isn't as discouraging for the other players, as it was when daewook was on top.  Thanks again.
