### ISSUE TITLE
Figure out Boost in cpp kit

### ISSUE THREAD

**Issue by Snaar** [HaliteChallenge/Halite-II#249]
From http://forums.halite.io/t/using-boost-headers-in-c/489/2

> Is there a good way to include boost's header-only libraries when building a c++ bot? The relative pathing requirement for headers means you have to replace every instance of
> #include "boost/config.hpp"
> with 
> #include "../../boost/config.hpp"
> or something similar.

**Comment by Snaar** [comment]
I was able to put "boost" directory out of boost distribution in the root of the bot, right next to "hlt" directory. Then I included "boost/crc.hpp" in MyBot.cpp and it compiled fine. It doesn't look like there is an issue.

**Comment by a-price** [comment]
Did you try any other files? The issue is the relative paths between boost files: a header will have another include directive like: `#include <boost/library/class.hpp>`, but since the bot directory isn't set as an include directory, the compiler can't find paths that just start with `boost`. One way to fix it would be to go through all boost files and replace every include that starts with `boost` with `../../boost`, but that would take some scripting work to accomplish.

As a test case, try adding `#include <boost/polygon/voronoi.hpp>` to your main file and see if that succeeds.

One possible workaround might be to add the bot's top-level directory to the include path, so that libraries didn't have to do fully relative addressing.

Thanks!

**Comment by Snaar** [comment]
#include <boost/polygon/voronoi.hpp> builds fine as well. What OS/compiler are you using?

**Comment by Snaar** [comment]
If you are building using cmake then the bot directory has already been included via `include_directories(${CMAKE_SOURCE_DIR})` in CMakeList.txt. If you were building on Windows I've  added `/I .` to the cl.exe invocation yesterday, so possibly it might be fixed already for you on Windows.

Closing for now, will reopen on more feedback.

**Comment by a-price** [comment]
Does the Halite server environment use the CMakeLists.txt? I couldn't find a reference to it in https://github.com/HaliteChallenge/Halite-II/blob/master/apiserver/worker/compiler.py

**Comment by Snaar** [comment]
Aha! Thanks for sticking with it. Yep, looks like this was completely missed. We should have entry for building if CMakeLists.txt is present. Filed #302.
