### ISSUE TITLE
old videos not loading

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#346]
I'm trying to watch a few old videos:
- /play/?game_id=2068027
- /play/?game_id=2843535

I know they're not replays because I linked to them in emails for email marketing and had tested them.

But now they won't play. Any thoughts @harikmenon?

**Comment by julskast** [comment]
Thanks for the extra detail @Janzert - makes sense to me that games are deleted after 2 weeks - I remember this work being done. But I thought we had a process to watch videos that had been deleted by pulling them out of the cloud bucket. I thought they could still be watched but with less detail. @lidavidm am I remembering this right?

**Comment by Janzert** [comment]
Yep there are the links you want are:

https://halite.io/play/?game_id=2068027&replay_class=1&replay_name=replay-20171031-141024%2B0000--1334776908-288-192-1509459000

https://halite.io/play/?game_id=2843535&replay_class=1&replay_name=replay-20171117-210851%2B0000--616142071-312-208-1510952930

 (the game_id paramater must be present but doesn't actually matter what it is)

**Comment by Janzert** [comment]
To be clear the game id is deleted from the database along with the rest of the game information. So there isn't a way to retrieve the replay from the game id once the game is deleted.

**Comment by lidavidm** [comment]
Yeah, it's an unfortunate kludge, but you need to make sure to open and wait for the game to load; while it does that, it'll change the URL to a permalink that should keep working even after the game is deleted from the database. Janzert is right, after that's done, there's no way to associate the game ID with the replay.

**Comment by julskast** [comment]
So @lidavidm thats what it used to do, but today it says 'can't load video': 
![image](https://user-images.githubusercontent.com/764613/33632726-8a994042-d9dc-11e7-93a4-2582b02a4395.png)

maybe it's having trouble changing the URL to the permalink?

**Comment by lidavidm** [comment]
Yeah, unfortunately, once it's been deleted on our end, it has no way to do
this anymore - Janzert just happens to have archives of past records so he
can still do it.

**Comment by julskast** [comment]
Sorry, maybe I'm confused about how this works. When does the game create a permalink? And how can it be a permalink if it stops working?

**Comment by lidavidm** [comment]
Sorry, it's a little convoluted. While the game is still in the database,
watching the game should silently rewrite the URL to the permalink - it's
much longer and will have replay_name and replay_class in the URL. That's
the URL you want to save. Once the game is deleted from the database, the
URL with only the game_id won't work anymore - you'll need to have the long
URL to watch it.

On Dec 5, 2017 16:55, "Julia" <notifications@github.com> wrote:

Sorry, maybe I'm confused about how this works. When does the game create a
permalink? And how can it be a permalink if it stops working?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/HaliteChallenge/Halite-II/issues/346#issuecomment-349454452>,
or mute the thread

**Comment by julskast** [comment]
Ok, starting to make sense. But then why doesn't this link work either? https://halite.io//play/?game_id=2843535&replay_class=1&replay_name=replay-20171117-210851+0000--616142071-312-208-1510952930

**Comment by lidavidm** [comment]
Hmm, that's definitely a bug. Looks like a URL encoding issue - it's interpreting the plus as a space, or rather, the plus should have been turned into %2B (wonder if there's some browser behavior tripping it up?). This URL works: https://halite.io//play/?game_id=2843535&replay_class=1&replay_name=replay-20171117-210851%2B0000--616142071-312-208-1510952930

**Comment by julskast** [comment]
We found the culprit to be a google analytics bug. Oy vey.
