### ISSUE TITLE
Map symmetry problems on 4-player maps

### ISSUE THREAD

**Issue by tmseiler** [HaliteChallenge/Halite-II#73]
I noticed that the players in this replay have different relative starting positions:

https://halite.io/play/?game_id=1866905&replay_class=0&replay_name=replay-20171025-033645%2B0000--3254658548-264-176-1508902574

The opposing corners are symmetrical, but they are not symmetrical to their adjacent corners.

**Comment by tmseiler** [comment]
This one's worse: https://halite.io/play/?game_id=1868774&replay_class=0&replay_name=replay-20171025-044354%2B0000--2958811381-288-192-1508906573

**Comment by tmseiler** [comment]
I checked some more maps last night, and this seemed to affect the majority of 4-player maps.

**Comment by harikmenon** [comment]
Chatting with @tmseiler on Discord on this this.

**Comment by Rampagy** [comment]
What was the outcome of this decision?  It was affected my game quite drastically (game can be found in the provided link).
https://forums.halite.io/t/game-map-not-symmetrical/390

**Comment by harikmenon** [comment]
We are still in active discussion, we have a prototype that generates perfectly symmetrical maps but they are super boring and make the game strategies a bit too uninteresting. 

Our analysis shows that over a large number of games, this is not a major factor. However, we are still looking at whether we can add a few symmetrical maps to the mix (we will not be getting rid of asymmetry completely)

**Comment by tmseiler** [comment]
On the last day of the competition -- assuming it will be like last year's -- are you ready to explain this to people who lose rank due to a string of unfair maps? And explain it to new players who are used to symmetry in essentially every other competitive game?

**Comment by tmseiler** [comment]
What about quantifying the starting positions of maps somehow and introducing a ranking/matchmaking handicap?

**Comment by shummie** [comment]
I hate the non-perfect symmetrical maps and I've voiced that enough. I do think that it yields more interesting games, but it does so in an unfair manner. Again, "given enough games" it all balances out at the end, and I think this means you'd need at least twice as many games (maybe more b/c of player position variance) in order to get back to get the same information as if the maps were perfectly symmetrical, which is fine if that's the solution.

What does hurt more is that losing games early on as a result of map imbalance means it's harder to recover later on due to how sigma/mu interact. Again, this could go either way which I don't think is ideal, but again, works itself out over a large enough set of games (which right now doesn't feel enough since so many bots are still < 400 games played so resubmission is SLOW to get back to your "true" rating). Is 400 games even enough to get an accurate representation of your rating? I don't know.

As for a string of unfair maps, yeah that sucks, but it's also part of the game. If we're going to accept that non perfect symmetrical maps are going to exist, then as long as enough games are played during the finals, a string of bad luck should hopefully not be an issue since sigma is now allowed to drop really low. You can see that daewook was able to play almost 100k games in the beta which basically means that a string of good or bad luck will have negligible impact on his rating. I don't know what the plans are and if the top X bots will be able to get anywhere near that # of games in the finals, but this is just a long way to say that increasing the # of games will solve this issue.

**Comment by tmseiler** [comment]
Yeah, I agree. What it means is that there's always going to be a question, especially if these maps are left unquantified, as to how many games are actually enough to smooth things out? And which ones should you ignore when you're doing personal development?

**Comment by shummie** [comment]
Maybe an option for local testing to produce perfectly symmetrical maps should be introduced? I agree, trying to test locally and seeing if you're improving is made more difficult than it should be.

**Comment by harikmenon** [comment]
@tmseiler @shummie - I think during the finals weeks, we will reset the scores just like last year and only play for players above Gold. Even if we get ~3K players, we are expecting 45 bots to compete in the finals. Given we are able to play 2000 odd games an hour, over 7 days each bot should get a chance to play atleast~7000+ games. I'm willing to double/triple our server counts for the week so theoretically we should able to get to 14000K games per bot. 

Given map/player variance, we believe this to be sufficient to stabilize the sigma to the point that it is fair.

@shummie - Curious, why would you need a local version of symmetrical maps, if we are not planning to have them on the servers?

**Comment by shummie** [comment]
I'm not worried about the finals if that many games are being played (as opposed to the 481 games in the halite 1 finals). 

As for local testing. I don't have the time / ability to do hundreds of games of testing on 4 player maps to see if my modifications are improving the bots. Since the asymmetry introduces additional variance in the results, being able to test on symmetrical maps would allow me to iterate faster.

**Comment by harikmenon** [comment]
Given we are at the end of the competition, closing this out. Will consider for Halite III
